In [32]:
import pandas as pd
import numpy as np
import seaborn as sns


from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv('heart.csv')

In [13]:
df.sample(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
866,44,M,ATA,130,219,0,LVH,188,N,0.0,Up,0
778,58,M,ASY,128,259,0,LVH,130,Y,3.0,Flat,1
551,62,M,NAP,120,220,0,LVH,86,N,0.0,Up,0
885,53,F,NAP,128,216,0,LVH,115,N,0.0,Up,0
864,60,M,ASY,145,282,0,LVH,142,Y,2.8,Flat,1
417,44,M,ASY,130,209,0,ST,127,N,0.0,Up,0
908,63,M,ASY,140,187,0,LVH,144,Y,4.0,Up,1
303,62,F,ASY,120,0,1,ST,123,Y,1.7,Down,1
657,44,M,NAP,130,233,0,Normal,179,Y,0.4,Up,0
358,38,M,NAP,115,0,0,Normal,128,Y,0.0,Flat,1

In [6]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [101]:
df.sample(3)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,ST_Slope,HeartDisease
454,58,M,ASY,136,203,1,Normal,123,Y,Flat,1
726,41,M,ATA,110,235,0,Normal,153,N,Up,0
249,49,M,ASY,130,341,0,Normal,120,Y,Flat,1

In [102]:
train_X,test_X,train_y,test_y = train_test_split(df.drop(columns=['HeartDisease']),df['HeartDisease'],test_size=0.2,random_state=42)

In [83]:
train_X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 734 entries, 759 to 34
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             734 non-null    int64
 1   Sex             734 non-null    object
 2   ChestPainType   734 non-null    object
 3   RestingBP       734 non-null    int64
 4   Cholesterol     734 non-null    int64
 5   FastingBS       734 non-null    int64
 6   RestingECG      734 non-null    object
 7   MaxHR           734 non-null    int64
 8   ExerciseAngina  734 non-null    object
 9   ST_Slope        734 non-null    object
dtypes: int64(5), object(5)
memory usage: 63.1+ KB

In [108]:
trf1 =ColumnTransformer([
    ('oe_ChestPainType',OrdinalEncoder(categories=[['ASY','NAP','ATA','TA']]),[2]),
    ('oe_RestingECG',OrdinalEncoder(categories=[['Normal','ST','LVH']]),[6]),
    ('oe_ExerciseAngina',OrdinalEncoder(categories=[['Y','N']]),[8]),
    ('oe_ST_Slop',OrdinalEncoder(categories=[['Flat','Up','Down']]),[9]),
    ('oe_sex',OrdinalEncoder(categories=[['M','F']]),[1])
],remainder='passthrough')

In [109]:
#Scaling
trf3=MinMaxScaler()

In [115]:
#feature Selection
trf4=SelectKBest(score_func=chi2,k=10)

In [116]:
#train the model
trf5=DecisionTreeClassifier(random_state=42)

In [117]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [120]:
pipe.fit(train_X,train_y)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('oe_ChestPainType',
                                                  OrdinalEncoder(categories=[['ASY',
                                                                              'NAP',
                                                                              'ATA',
                                                                              'TA']]),
                                                  [2]),
                                                 ('oe_RestingECG',
                                                  OrdinalEncoder(categories=[['Normal',
                                                                              'ST',
                                                                              'LVH']]),
                                                  [6]),
                                                 ('oe_ExerciseAngina',
                                                  OrdinalEncoder(categories=[['Y',
                                                                              'N']]),
                                                  [8]),
                                                 ('oe_ST_Slop',
                                                  OrdinalEncoder(categories=[['Flat',
                                                                              'Up',
                                                                              'Down']]),
                                                  [9]),
                                                 ('oe_sex',
                                                  OrdinalEncoder(categories=[['M',
                                                                              'F']]),
                                                  [1])])),
                ('trf3', MinMaxScaler()),
                ('trf4',
                 SelectKBest(score_func=<function chi2 at 0x0000011822B6C860>)),
                ('trf5', DecisionTreeClassifier(random_state=42))])

In [121]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('oe_ChestPainType',
                                  OrdinalEncoder(categories=[['ASY', 'NAP',
                                                              'ATA', 'TA']]),
                                  [2]),
                                 ('oe_RestingECG',
                                  OrdinalEncoder(categories=[['Normal', 'ST',
                                                              'LVH']]),
                                  [6]),
                                 ('oe_ExerciseAngina',
                                  OrdinalEncoder(categories=[['Y', 'N']]), [8]),
                                 ('oe_ST_Slop',
                                  OrdinalEncoder(categories=[['Flat', 'Up',
                                                              'Down']]),
                                  [9]),
                                 ('oe_sex',
                                  OrdinalEncoder(categories=[['M', 'F']]),
                                  [1])]),
 'trf3': MinMaxScaler(),
 'trf4': SelectKBest(score_func=<function chi2 at 0x0000011822B6C860>),
 'trf5': DecisionTreeClassifier(random_state=42)}

In [122]:
from sklearn import set_config

In [123]:
set_config(display='diagram')

In [129]:
y_pred = pipe.predict(test_X)

In [130]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,y_pred)

0.8206521739130435

In [131]:
#cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe,train_X,train_y,cv=5,scoring='accuracy').mean()

np.float64(0.7601714658466125)

In [132]:
params = {
    'trf5__max_depth':[1,2,3,4,5,None]
}

In [133]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

In [134]:
test_X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,ST_Slope
668,63,F,ATA,140,195,0,Normal,179,N,Up
30,53,M,NAP,145,518,0,Normal,130,N,Flat
377,65,M,ASY,160,0,1,ST,122,N,Flat
535,56,M,ASY,130,0,0,LVH,122,Y,Flat
807,54,M,ATA,108,309,0,Normal,156,N,Up
...,...,...,...,...,...,...,...,...,...,...
211,50,F,NAP,140,288,0,Normal,140,Y,Flat
745,63,F,ASY,108,269,0,Normal,169,Y,Flat
584,64,M,ASY,141,244,1,ST,116,Y,Flat
878,49,M,ATA,130,266,0,Normal,171,N,Up
451,64,M,ASY,144,0,0,ST,122,Y,Flat